version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      FRONTEND_URL: http://localhost:8080
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: votre_secret_jwt_tres_securise_a_changer
    networks:
      - skribble-net

volumes:
  postgres-data:

networks:
  skribble-net:
